export type contract = {
  address: string;
  constructorArgs: string | number[];
}

declare module '@fiatdao/changelog' {
  interface goerli {
    deployer: contract;
    aerFactory: contract;
    codexFactory: contract;
    collateralAuctionFactory: contract;
    collybusFactory: contract;
    debtAuctionFactory: contract;
    fiatFactory: contract;
    limesFactory: contract;
    monetaFactory: contract;
    priceCalculatorFactory: contract;
    publicanFactory: contract;
    surplusAuctionFactory: contract;
    tenebraeFactory: contract;
    aer: contract;
    codex: contract;
    collybus: contract;
    fiat: contract;
    debtAuction: contract;
    limes: contract;
    moneta: contract;
    collateralAuction: contract;
    publican: contract;
    surplusAuction: contract;
    tenebrae: contract;
    proxyFactory: contract;
    proxyRegistry: contract;
    noLossCollateralAuctionActions: contract;
    vaultEPTActions: contract;
    delphiChainlinkFactory: contract;
    spotRelayer_USDC: contract;
    chainlinkValueProvider_USDC: contract;
    spotRelayer_DAI: contract;
    chainlinkValueProvider_DAI: contract;
    delphiLUSD3CRVFactory: contract;
    spotRelayer_LUSD3CRV: contract;
    chainlinkValueProvider_LUSD3CRV: contract;
    delphiRelayerFactory: contract;
    discountRateRelayer_ePyvUSDC: contract;
    discountRateRelayer_ePyvDAI: contract;
    discountRateRelayer_ePyvLUSD3CRV: contract;
    aerGuard: contract;
    auctionGuard: contract;
    codexGuard: contract;
    collybusGuard: contract;
    limesGuard: contract;
    publicanGuard: contract;
    vaultGuard: contract;
    vaultFactory: contract;
    vaultEPT_ePyvUSDC_Impl_62d985: contract;
    vaultEPT_ePyvUSDC_29APR22: contract;
    vaultEPT_ePyvDAI_Impl_21BbC0: contract;
    vaultEPT_ePyvDAI_29APR22: contract;
    vaultEPT_ePyvLUSD3CRV_Impl_53b1aE: contract;
    vaultEPT_ePyvLUSD3CRV_29APR22: contract;
    vaultEPT_ePyvUSDC_impl_57A170: contract;
    vaultEPT_ePyvUSDC_16SEP22: contract;
    vaultEPT_ePyvDAI_impl_3A285c: contract;
    vaultEPT_ePyvDAI_16SEP22: contract;
    vaultEPT_ePyvLUSD3CRV_impl_55Ae42: contract;
    vaultEPT_ePyvLUSD3CRV_16SEP22: contract;
  }

  interface mainnet {
    deployer: contract;
    aerFactory: contract;
    codexFactory: contract;
    collateralAuctionFactory: contract;
    collybusFactory: contract;
    debtAuctionFactory: contract;
    fiatFactory: contract;
    limesFactory: contract;
    monetaFactory: contract;
    priceCalculatorFactory: contract;
    publicanFactory: contract;
    surplusAuctionFactory: contract;
    tenebraeFactory: contract;
    aer: contract;
    codex: contract;
    collybus: contract;
    fiat: contract;
    debtAuction: contract;
    limes: contract;
    moneta: contract;
    collateralAuction: contract;
    publican: contract;
    surplusAuction: contract;
    tenebrae: contract;
    proxyFactory: contract;
    proxyRegistry: contract;
    noLossCollateralAuctionActions: contract;
    vaultEPTActions: contract;
    delphiChainlinkFactory: contract;
    spotRelayer_USDC: contract;
    chainlinkValueProvider_USDC: contract;
    spotRelayer_DAI: contract;
    chainlinkValueProvider_DAI: contract;
    delphiLUSD3CRVFactory: contract;
    spotRelayer_LUSD3CRV: contract;
    chainlinkValueProvider_LUSD3CRV: contract;
    delphiRelayerFactory: contract;
    discountRateRelayer_ePyvUSDC: contract;
    discountRateRelayer_ePyvDAI: contract;
    discountRateRelayer_ePyvLUSD3CRV: contract;
    aerGuard: contract;
    auctionGuard: contract;
    codexGuard: contract;
    collybusGuard: contract;
    limesGuard: contract;
    publicanGuard: contract;
    vaultGuard: contract;
    vaultFactory: contract;
    vaultEPT_ePyvUSDC_Impl_62d985: contract;
    vaultEPT_ePyvUSDC_29APR22: contract;
    vaultEPT_ePyvDAI_Impl_21BbC0: contract;
    vaultEPT_ePyvDAI_29APR22: contract;
    vaultEPT_ePyvLUSD3CRV_Impl_53b1aE: contract;
    vaultEPT_ePyvLUSD3CRV_29APR22: contract;
    vaultEPT_ePyvUSDC_impl_57A170: contract;
    vaultEPT_ePyvUSDC_16SEP22: contract;
    vaultEPT_ePyvDAI_impl_3A285c: contract;
    vaultEPT_ePyvDAI_16SEP22: contract;
    vaultEPT_ePyvLUSD3CRV_impl_55Ae42: contract;
    vaultEPT_ePyvLUSD3CRV_16SEP22: contract;
  }

  export {goerli, mainnet};
}
